Added Scoop acceptance testing after release

diff --git a/.github/workflows/platform-executables-acceptance-tests.yml b/.github/workflows/platform-executables-acceptance-tests.yml
--- a/.github/workflows/platform-executables-acceptance-tests.yml
+++ b/.github/workflows/platform-executables-acceptance-tests.yml
@@ -166,12 +166,41 @@ jobs:
         if: failure() || cancelled()
         id: failure_debian
         run: echo '::set-output name=FAILURE_TAG_DEBIAN::true'
+  
+  test-scoop-release:
+    name: Do scoop testing after release
+    runs-on: windows-latest
+    continue-on-error: true
+    needs: [ get-branch, get-tag ]
+    outputs:
+      FAILURE_TAG_SCOOP: ${{ steps.failure_scoop.outputs.FAILURE_TAG_SCOOP }}
+    steps:
+      - name: Checkout cli repo
+        uses: actions/checkout@v2
+      - name: Wait for Scoop release to finish
+        run: source .github/scripts/trigger-and-wait.sh
+        env:
+          INPUT_WORKFLOW_FILE_NAME: oclif-release.yml
+          INPUT_REF: ${{ needs.get-branch.outputs.branch }}
+      - name: Perform testing on scoop installations
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          iwr -useb get.scoop.sh | iex
+          scoop bucket add twilio-scoop https://github.com/twilio/scoop-twilio-cli
+          scoop install twilio
+          twilio --version
+          twilio api --help
+      - name: setup scoop failure output
+        if: failure() || cancelled()
+        id: failure_scoop
+        run: echo '::set-output name=FAILURE_TAG_SCOOP::true'
 
   notify-complete-fail:
     needs: [wait-for-oclif-releases, wait-for-windows-releases, wait-for-debian-releases, wait-for-macos-releases]
     name: Notify Release Failed
     runs-on: ubuntu-latest
-    if: ${{ ( needs.wait-for-macos-releases.outputs.FAILURE_TAG_MACOS == 'true' ) || ( needs.wait-for-windows-releases.outputs.FAILURE_TAG_WINDOWS == 'true' ) || ( needs.wait-for-oclif-releases.outputs.FAILURE_TAG_OCLIF  == 'true' ) || ( needs.wait-for-debian-releases.outputs.FAILURE_TAG_DEBIAN == 'true') }}
+    if: ${{ ( needs.wait-for-macos-releases.outputs.FAILURE_TAG_MACOS == 'true' ) || ( needs.wait-for-windows-releases.outputs.FAILURE_TAG_WINDOWS == 'true' ) || ( needs.wait-for-oclif-releases.outputs.FAILURE_TAG_OCLIF  == 'true' ) || ( needs.wait-for-debian-releases.outputs.FAILURE_TAG_DEBIAN == 'true') || ( needs.test-scoop-release.outputs.FAILURE_TAG_SCOOP == 'true') }}
     steps:
       - uses: actions/checkout@v2
       - name: Slack Notification
@@ -184,6 +213,6 @@ jobs:
           SLACK_TITLE: "Twilio Cli"
           SLACK_MESSAGE: 'CLI acceptance workflow Failed'
       - name: Fail in case all jobs failed
-        if: ${{ ( needs.wait-for-macos-releases.outputs.FAILURE_TAG_MACOS == 'true' ) && ( needs.wait-for-windows-releases.outputs.FAILURE_TAG_WINDOWS == 'true' ) && ( needs.wait-for-oclif-releases.outputs.FAILURE_TAG_OCLIF  == 'true' ) && ( needs.wait-for-debian-releases.outputs.FAILURE_TAG_DEBIAN == 'true') }}
+        if: ${{ ( needs.wait-for-macos-releases.outputs.FAILURE_TAG_MACOS == 'true' ) && ( needs.wait-for-windows-releases.outputs.FAILURE_TAG_WINDOWS == 'true' ) && ( needs.wait-for-oclif-releases.outputs.FAILURE_TAG_OCLIF  == 'true' ) && ( needs.wait-for-debian-releases.outputs.FAILURE_TAG_DEBIAN == 'true') && ( needs.test-scoop-release.outputs.FAILURE_TAG_SCOOP == 'true')}}
         run:
           exit 1
